import{a as h,S as _,i as b}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();const L=async({value:e,page:t})=>await h.get("https://pixabay.com/api/",{params:{key:"42682169-5194f534d6ac320016f3b6be7",q:e,image_type:"photo",pretty:!0,page:t,per_page:15}}),c=document.querySelector(".gallery"),S=e=>e.map(({largeImageURL:t,webformatURL:o,tags:a,likes:s,views:r,comments:n,downloads:f})=>`
        <li class="gallery__item">
            <a href="${t}" class="gallery__link"
                ><img src="${o}" alt="${a}" class="gallery__image"
            /></a>
            <div class="gallery__description">
                <p class="gallery__text"><strong>Likes</strong> <span>${s}</span></p>
                <p class="gallery__text"><strong>Views</strong> <span>${r}</span></p>
                <p class="gallery__text"><strong>Comments</strong> <span>${n}</span></p>
                <p class="gallery__text"><strong>Downloads</strong> <span>${f}</span></p>
            </div>
        </li>
      `).join(""),v=e=>{c.insertAdjacentHTML("beforeend",S(e))};c.addEventListener("click",e=>{e.preventDefault(),new _("a",{captionsData:"alt",captionDelay:250}).open()});const p=document.querySelector(".js-form"),d=document.querySelector('button[type="submit"]'),l=document.querySelector(".load-more"),w=document.querySelector(".loader"),u=(e,t)=>b.show({message:e,messageColor:t,position:"topCenter"}),y=e=>w.style.display=e,i=({elem:e,disabled:t=!1,display:o})=>{e.style.display=o,e.disabled=t};let g=1;const m=async({value:e,page:t=1})=>{y("block"),i({elem:d,disabled:!0});const o=await L({value:e,page:t});if(i({elem:d}),y("none"),o.status===200){const{data:a}=o;a.hits.length?v(a.hits):u("Sorry, there are no images matching your search query. Please try again!","green")}else u("Something went wrong. Please try again","red")};p.addEventListener("submit",async e=>{e.preventDefault();const t=e.currentTarget.elements["js-input"].value;t&&(c.innerHTML="",l.style.display==="block"&&i({elem:l,display:"none"}),await m({value:t}),i({elem:l,display:"block"})),p.reset()});l.addEventListener("click",()=>{g++,m({page:g})});
//# sourceMappingURL=commonHelpers.js.map
