import{a as b,S as L,i as S}from"./assets/vendor-64b55ca9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const w=async({value:e,page:s})=>await b.get("https://pixabay.com/api/",{params:{key:"42682169-5194f534d6ac320016f3b6be7",q:e,image_type:"photo",pretty:!0,page:s,per_page:15}}),d=document.querySelector(".gallery"),v=e=>e.map(({largeImageURL:s,webformatURL:o,tags:a,likes:t,views:r,comments:n,downloads:_})=>`
        <li class="gallery__item">
            <a href="${s}" class="gallery__link"
                ><img src="${o}" alt="${a}" class="gallery__image"
            /></a>
            <div class="gallery__description">
                <p class="gallery__text"><strong>Likes</strong> <span>${t}</span></p>
                <p class="gallery__text"><strong>Views</strong> <span>${r}</span></p>
                <p class="gallery__text"><strong>Comments</strong> <span>${n}</span></p>
                <p class="gallery__text"><strong>Downloads</strong> <span>${_}</span></p>
            </div>
        </li>
      `).join(""),q=e=>{d.insertAdjacentHTML("beforeend",v(e))};d.addEventListener("click",e=>{e.preventDefault(),new L("a",{captionsData:"alt",captionDelay:250}).open()});const p=document.querySelector(".js-form"),y=document.querySelector('button[type="submit"]'),l=document.querySelector(".load-more"),x=document.querySelector(".loader"),u=(e,s)=>S.show({message:e,messageColor:s,position:"topCenter"}),g=e=>x.style.display=e,i=({elem:e,disabled:s=!1,display:o})=>{e.style.display=o,e.disabled=s},f=()=>{i({elem:l,display:"none"}),u("We're sorry, but you've reached the end of search results.","green")};let m=1,c;const M=l.style.display==="block",h=async({value:e,page:s=1})=>{g("block"),i({elem:y,disabled:!0});const o=await w({value:e,page:s});if(i({elem:y}),g("none"),o.status===200){const{data:a}=o;a.hits.length?q(a.hits):u("Sorry, there are no images matching your search query. Please try again!","green")}else u("Something went wrong. Please try again","red");return o};p.addEventListener("submit",async e=>{e.preventDefault(),c=e.currentTarget.elements["js-input"].value,c&&(d.innerHTML="",M&&i({elem:l,display:"none"}),(await h({value:c})).data.hits.length<15?f():i({elem:l,display:"block"})),p.reset()});l.addEventListener("click",async()=>{m++,(await h({value:c,page:m})).data.hits.length<15&&f()});
//# sourceMappingURL=commonHelpers.js.map
